// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ8xIIQ-uyH9woG-9zgNfvGqjUUkEEdpM',
    appId: '1:504739675335:web:13ce8d4dc349eb49af92e2',
    messagingSenderId: '504739675335',
    projectId: 'task-manager-1cb03',
    authDomain: 'task-manager-1cb03.firebaseapp.com',
    storageBucket: 'task-manager-1cb03.firebasestorage.app',
    measurementId: 'G-RE1R0VND3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeGRWMz7wzwgAVyX40spVdX9J_MA-v_Ac',
    appId: '1:504739675335:android:d72aaf86ccc205f4af92e2',
    messagingSenderId: '504739675335',
    projectId: 'task-manager-1cb03',
    storageBucket: 'task-manager-1cb03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2zg75NwTEORHVaQMGhgZ6m3rvy7HWOjw',
    appId: '1:504739675335:ios:77cd21fa6ab3e1caaf92e2',
    messagingSenderId: '504739675335',
    projectId: 'task-manager-1cb03',
    storageBucket: 'task-manager-1cb03.firebasestorage.app',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2zg75NwTEORHVaQMGhgZ6m3rvy7HWOjw',
    appId: '1:504739675335:ios:77cd21fa6ab3e1caaf92e2',
    messagingSenderId: '504739675335',
    projectId: 'task-manager-1cb03',
    storageBucket: 'task-manager-1cb03.firebasestorage.app',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ8xIIQ-uyH9woG-9zgNfvGqjUUkEEdpM',
    appId: '1:504739675335:web:be25f22ce7f7d1e6af92e2',
    messagingSenderId: '504739675335',
    projectId: 'task-manager-1cb03',
    authDomain: 'task-manager-1cb03.firebaseapp.com',
    storageBucket: 'task-manager-1cb03.firebasestorage.app',
    measurementId: 'G-7R8NXPCBPC',
  );
}
